import { execFile } from "node:child_process";
import path from "node:path";
import { promisify } from "node:util";
import {
  CliError,
  DEFAULT_DAILY_AT,
  DEFAULT_TASK_NAME,
  EXIT_CODES
} from "../cli/command-registry.js";
import { hhmmSchema } from "../config/config.model.js";
import { getSchedulerLauncherPath, writeTextCreatingParent } from "../config/runtime-files.js";
import { hasTokenLikeArgument, sanitizeText } from "../utils/masking.js";

const execFileAsync = promisify(execFile);
export const HIDDEN_SCHEDULER_MODE = "hidden background";
export const HIDDEN_SCHEDULER_EXECUTABLE = "wscript.exe";

export type ScheduledCommand = {
  execute: string;
  arguments: string[];
  commandLine: string;
};

type ScheduledTaskAction = {
  execute: string;
  arguments: string;
  wrapperScriptPath: string;
  wrapperScriptContent: string;
  mode: typeof HIDDEN_SCHEDULER_MODE;
};

export type SchedulerStatus = {
  exists: boolean;
  taskName: string;
  nextRunTime?: string;
  lastRunTime?: string;
  lastResultCode?: number;
  registeredCommand?: string;
  mode?: typeof HIDDEN_SCHEDULER_MODE;
};

export type SchedulerCommandInput = {
  cliCommand?: string;
  nodeExecutable?: string;
  cliScriptPath?: string;
  configPath: string;
};

export type SchedulerOptions = {
  taskName?: string;
  dailyAt?: string;
  configPath: string;
  cliCommand?: string;
  nodeExecutable?: string;
  cliScriptPath?: string;
  appDataDirectory?: string;
  executor?: PowerShellExecutor;
  wrapperScriptPath?: string;
  writeWrapperScript?: (filePath: string, content: string) => Promise<void>;
};

export type PowerShellExecutor = (script: string) => Promise<string>;

function quoteArg(value: string): string {
  if (!/[\s"]|^[A-Za-z]:\\/.test(value)) {
    return value;
  }
  return `"${value.replace(/"/g, '\\"')}"`;
}

function psQuote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function vbString(value: string): string {
  return `"${value.replace(/"/g, '""')}"`;
}

export function buildScheduledSyncCommand(input: SchedulerCommandInput): ScheduledCommand {
  const execute =
    input.cliCommand ??
    (input.cliScriptPath ? input.nodeExecutable ?? process.execPath : "mono-lunchmoney");
  const scriptPath = input.cliCommand ? undefined : input.cliScriptPath;
  const args = [
    ...(scriptPath ? [path.resolve(scriptPath)] : []),
    "sync",
    "--config",
    input.configPath,
    "--quiet"
  ];

  if (hasTokenLikeArgument([execute, ...args])) {
    throw new CliError("Scheduled command must not contain token arguments.", EXIT_CODES.USER_ERROR);
  }

  return {
    execute,
    arguments: args,
    commandLine: [quoteArg(execute), ...args.map(quoteArg)].join(" ")
  };
}

export function buildHiddenScheduledTaskAction(
  command: ScheduledCommand,
  wrapperScriptPath: string
): ScheduledTaskAction {
  const wrapperScriptContent = [
    "' Generated by mono-lunchmoney. Do not add secrets to this file.",
    `' mono-lunchmoney-scheduler-command: ${command.commandLine}`,
    `' mono-lunchmoney-scheduler-mode: ${HIDDEN_SCHEDULER_MODE}`,
    "Option Explicit",
    "Dim shell",
    "Dim exitCode",
    "Dim command",
    `command = ${vbString(command.commandLine)}`,
    'Set shell = CreateObject("WScript.Shell")',
    "exitCode = shell.Run(command, 0, True)",
    "WScript.Quit exitCode"
  ].join("\r\n");
  const args = ["//B", "//Nologo", wrapperScriptPath];

  if (hasTokenLikeArgument([command.execute, ...command.arguments, ...args, wrapperScriptContent])) {
    throw new CliError("Scheduled command must not contain token arguments.", EXIT_CODES.USER_ERROR);
  }

  return {
    execute: HIDDEN_SCHEDULER_EXECUTABLE,
    arguments: args.map(quoteArg).join(" "),
    wrapperScriptPath,
    wrapperScriptContent,
    mode: HIDDEN_SCHEDULER_MODE
  };
}

export function parseSchedulerStatus(raw: string, taskName = DEFAULT_TASK_NAME): SchedulerStatus {
  const trimmed = raw.trim();
  if (!trimmed || trimmed === "null") {
    return { exists: false, taskName };
  }

  const parsed = JSON.parse(trimmed) as {
    TaskName?: string;
    NextRunTime?: string;
    LastRunTime?: string;
    LastTaskResult?: number;
    Execute?: string;
    Arguments?: string;
    RegisteredCommand?: string;
    Mode?: typeof HIDDEN_SCHEDULER_MODE;
  };

  const execute = parsed.Execute ?? "";
  const args = parsed.Arguments ?? "";
  const command =
    parsed.RegisteredCommand ??
    parseHiddenScheduledTaskCommand(execute, args) ??
    buildSanitizedFallbackCommand(execute, args);
  const mode =
    parsed.Mode ?? (/(^|\\)(?:wscript|cscript)(?:\.exe)?$/i.test(execute) ? HIDDEN_SCHEDULER_MODE : undefined);

  return {
    exists: true,
    taskName: parsed.TaskName ?? taskName,
    nextRunTime: parsed.NextRunTime,
    lastRunTime: parsed.LastRunTime,
    lastResultCode: parsed.LastTaskResult,
    registeredCommand: command ? sanitizeText(command) : undefined,
    mode
  };
}

function parseHiddenScheduledTaskCommand(execute: string, args: string): string | undefined {
  if (/(^|\\)(?:wscript|cscript)(?:\.exe)?$/i.test(execute)) {
    return undefined;
  }

  if (!/(^|\\)(?:powershell|pwsh)(?:\.exe)?$/i.test(execute)) {
    return undefined;
  }

  const filePath = args.match(/Start-Process\s+-FilePath\s+'((?:''|[^'])*)'/i)?.[1];
  const argList = args.match(/-ArgumentList\s+@\((.*?)\)\s+-WindowStyle/is)?.[1];
  if (!filePath || !argList) {
    return undefined;
  }

  const parsedArgs = [...argList.matchAll(/'((?:''|[^'])*)'/g)].map((match) =>
    match[1].replace(/''/g, "'")
  );
  if (parsedArgs.length === 0) {
    return undefined;
  }

  return [filePath.replace(/''/g, "'"), ...parsedArgs].map(quoteArg).join(" ");
}

function buildSanitizedFallbackCommand(execute: string, args: string): string | undefined {
  if (/(^|\\)(?:wscript|cscript)(?:\.exe)?$/i.test(execute)) {
    return "mono-lunchmoney sync --quiet (hidden launcher metadata unavailable)";
  }
  return [execute, args].filter(Boolean).join(" ");
}

export async function defaultPowerShellExecutor(script: string): Promise<string> {
  const executable = process.env.ComSpec ? "powershell.exe" : "pwsh";
  const { stdout } = await execFileAsync(executable, [
    "-NoProfile",
    "-ExecutionPolicy",
    "Bypass",
    "-Command",
    script
  ]);
  return stdout;
}

function assertWindows(): void {
  if (process.platform !== "win32") {
    throw new CliError("Windows Task Scheduler is only available on Windows.", EXIT_CODES.EXTERNAL_ERROR);
  }
}

export async function installScheduledTask(options: SchedulerOptions): Promise<ScheduledCommand> {
  if (!options.executor) {
    assertWindows();
  }
  const dailyAt = hhmmSchema.parse(options.dailyAt ?? DEFAULT_DAILY_AT);
  const taskName = options.taskName ?? DEFAULT_TASK_NAME;
  const scheduled = buildScheduledSyncCommand({
    configPath: options.configPath,
    cliCommand: options.cliCommand,
    nodeExecutable: options.nodeExecutable,
    cliScriptPath: options.cliScriptPath
  });
  const wrapperScriptPath =
    options.wrapperScriptPath ??
    getSchedulerLauncherPath(options.appDataDirectory ?? path.dirname(options.configPath), taskName);
  const taskAction = buildHiddenScheduledTaskAction(scheduled, wrapperScriptPath);
  if (!options.executor || options.writeWrapperScript || options.wrapperScriptPath) {
    try {
      await (options.writeWrapperScript ?? writeTextCreatingParent)(
        taskAction.wrapperScriptPath,
        taskAction.wrapperScriptContent
      );
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      throw new CliError(
        `Unable to prepare hidden scheduler launcher: ${message}`,
        EXIT_CODES.EXTERNAL_ERROR
      );
    }
  }
  const executor = options.executor ?? defaultPowerShellExecutor;
  const script = [
    `$Action = New-ScheduledTaskAction -Execute ${psQuote(taskAction.execute)} -Argument ${psQuote(
      taskAction.arguments
    )}`,
    `$Trigger = New-ScheduledTaskTrigger -Daily -At ${psQuote(dailyAt)}`,
    "$Settings = New-ScheduledTaskSettingsSet -MultipleInstances IgnoreNew -StartWhenAvailable -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries",
    `Register-ScheduledTask -TaskName ${psQuote(taskName)} -Action $Action -Trigger $Trigger -Settings $Settings -Description ${psQuote(
      "Daily Monobank to Lunch Money transaction sync"
    )} -Force | Out-Null`
  ].join("; ");

  await executor(script);
  return scheduled;
}

export async function getScheduledTaskStatus(
  taskName = DEFAULT_TASK_NAME,
  executor: PowerShellExecutor = defaultPowerShellExecutor
): Promise<SchedulerStatus> {
  if (process.platform !== "win32" && executor === defaultPowerShellExecutor) {
    return { exists: false, taskName };
  }

  const script = [
    "$ErrorActionPreference = 'Stop'",
    `$Task = $null`,
    `try { $Task = Get-ScheduledTask -TaskName ${psQuote(taskName)} -ErrorAction Stop } catch { exit 0 }`,
    "if ($null -eq $Task) { exit 0 }",
    "$Info = Get-ScheduledTaskInfo -TaskName $Task.TaskName",
    "$Action = @($Task.Actions)[0]",
    "$RegisteredCommand = $null",
    "$Mode = $null",
    "$ScriptPath = $null",
    `if ($Action.Execute -match '(?i)(^|\\\\)wscript(\\.exe)?$') { $Mode = ${psQuote(
      HIDDEN_SCHEDULER_MODE
    )}; if ($Action.Arguments -match '(?:^|\\s)(?:"([^"]+\\.vbs)"|(\\S+\\.vbs))(?:\\s|$)') { $ScriptPath = if ($Matches[1]) { $Matches[1] } else { $Matches[2] } } }`,
    "if ($ScriptPath -and (Test-Path -LiteralPath $ScriptPath)) { $Content = Get-Content -LiteralPath $ScriptPath -Raw; if ($Content -match \"(?m)^'\\s*mono-lunchmoney-scheduler-command:\\s*(.+)$\") { $RegisteredCommand = $Matches[1].Trim() } elseif ($Content -match 'command = \"((?:[^\"]|\"\")*)\"') { $RegisteredCommand = $Matches[1].Replace('\"\"', '\"') }; if ($Content -match \"(?m)^'\\s*mono-lunchmoney-scheduler-mode:\\s*(.+)$\") { $Mode = $Matches[1].Trim() } }",
    "[PSCustomObject]@{ TaskName = $Task.TaskName; NextRunTime = $Info.NextRunTime; LastRunTime = $Info.LastRunTime; LastTaskResult = $Info.LastTaskResult; Execute = $Action.Execute; Arguments = $Action.Arguments; RegisteredCommand = $RegisteredCommand; Mode = $Mode } | ConvertTo-Json -Compress"
  ].join("; ");

  const stdout = await executor(script);
  return parseSchedulerStatus(stdout, taskName);
}

export async function uninstallScheduledTask(
  taskName = DEFAULT_TASK_NAME,
  executor: PowerShellExecutor = defaultPowerShellExecutor
): Promise<void> {
  if (executor === defaultPowerShellExecutor) {
    assertWindows();
  }
  const script = [
    `$Task = Get-ScheduledTask -TaskName ${psQuote(taskName)} -ErrorAction SilentlyContinue`,
    "if ($null -ne $Task) { Unregister-ScheduledTask -TaskName $Task.TaskName -Confirm:$false }"
  ].join("; ");
  await executor(script);
}
